export const PRIMARY_QUERY = 'PRIMARY_QUERY';
export const FETCH_STATIONLIST = 'FETCH_STATIONLIST';
export const ACTIVE_STATION = 'ACTIVE_STATION';
export const FETCH_GIFLIST = 'FETCH_GIFLIST';
export const ACTIVE_GIF = 'ACTIVE_GIF';
