export const PRIMARY_QUERY = 'PRIMARY_QUERY';
export const FETCH_STATIONLIST = 'FETCH_STATIONLIST';
export const ACTIVE_STATION = 'ACTIVE_STATION';
export const FETCH_GIFLIST = 'FETCH_GIFLIST';
export const ACTIVE_GIF = 'ACTIVE_GIF';
export const DISPLAY_CONTROL_PANEL = 'DISPLAY_CONTROL_PANEL';
export const DISPLAY_GIF_PANEL = 'DISPLAY_GIF_PANEL';
